export const REQUEST_FETCH: string = 'REQUEST_FETCH';
export const FETCH_FAILED: string = 'FETCH_FAILED';
export const MOVIE_GET_NOW_PLAYING: string = 'MOVIE_GET_NOW_PLAYING';
export const MOVIE_GET_MOVIE_DETAILS: string = 'MOVIE_GET_MOVIE_DETAILS';
export const MOVIE_GET_RECCOMENDATION: string = 'MOVIE_GET_RECCOMENDATION';
export const MOVIE_GET_CREDITS: string = 'MOVIE_GET_CREDITS';
