export const REQUEST_FETCH: string = 'REQUEST_FETCH';
export const FETCH_FAILED: string = 'FETCH_FAILED';
export const MOVIE_GET_NOW_PLAYING: string = 'MOVIE_GET_NOW_PLAYING';
export const MOVIE_GET_MOVIE_DETAILS: string = 'MOVIE_GET_MOVIE_DETAILS';
export const MOVIE_GET_RECCOMENDATION: string = 'MOVIE_GET_RECCOMENDATION';
export const MOVIE_GET_CREDITS: string = 'MOVIE_GET_CREDITS';
export const PEOPLE_GET_DETAILS: string = 'PEOPLE_GET_DETAILS';
export const SEARCH_REQUESTED: string = 'SEARCH_REQUESTED';
export const SEARCH_RESULTS: string = 'SEARCH_RESULTS';
export const SEARCH_FAILED: string = 'SEARCH_FAILED';
export const SERIE_GET_TOP_RATED: string = 'SERIE_GET_TOP_RATED';
export const SERIE_GET_SERIE_DETAILS: string = 'SERIE_GET_SERIE_DETAILS';
export const SERIE_GET_RECCOMENDATION: string = 'SERIE_GET_RECCOMENDATION';
export const SERIE_GET_CREDITS: string = 'SERIE_GET_CREDITS';



